name: Build MouseLoader
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: true
        install: >-
          mingw-w64-i686-gcc

    - name: Compile with g++ (32-bit, static)
      shell: msys2 {0}
      run: |
        g++ main.cpp -o RE4-MouseLoader.exe -mwindows -luser32 -static -static-libgcc -static-libstdc++

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RE4-MouseLoader
        path: RE4-MouseLoader.exe
